### ISSUE TITLE
Referenzen auf Formeln funktionieren nicht

### ISSUE THREAD

**Issue by ktiu** [s2742970/2021_statistische_verfahren#1]
Latex hatte "\autoref",  das scheint hier nicht zu funktionieren

**Comment by s2742970** [comment]
Habe "\autoref" mit "\@ref" ersetzt, Formeln mit gleichen Labels werden aber noch nicht richtig nummeriert

**Comment by s2742970** [comment]
Referenzen funktionieren jetzt. Habe bei gleichen Labels die Sitzungsnummer hinzugefügt (z. B.: statt "var" "4var")
